#ifndef FizVizNeedleSettings_h
#define FizVizNeedleSettings_h

typedef enum NEEDLE_DIRECTION_TAG
{
  NEEDLE_DIRECTION_CLOCKWISE,
  NEEDLE_DIRECTION_COUNTERCLOCKWISE,
  NEEDLE_DIRECTION_CLOSEST,
  NEEDLE_DIRECTION_DO_NOT_PASS_ZERO
} NEEDLE_DIRECTION;

#endif
